### ISSUE TITLE
Byteplay doesn't work with Python 3.5

### ISSUE THREAD

**Issue by sashw** [rootpy/rootpy#671]
rootpy deosn't work anymore with Python 3.5. If I try something like
`from rootpy.plotting import Canvas`
I get a `NameError` which tells me that "WITH_CLEANUP" is not defined. This has been renamed in the `dis` package in Python 3.5, there are now WITH_CLEANUP_START and WITH_CLEANUP_FINISH: https://docs.python.org/3.5/library/dis.html

**Comment by sashw** [comment]
Filed also an issue in the byteplay repository: https://github.com/serprex/byteplay/issues/4

**Comment by peterazmanov** [comment]
@sashw in my [byteplay fork](https://github.com/peterazmanov/byteplay) I added support for Python 3.5 and tested it with recompile-Python-Lib. You can give it a try.

**Comment by pwaller** [comment]
Note: we imported byteplay into [`/rootpy/extern`](https://github.com/rootpy/rootpy/tree/master/rootpy/extern), so someone will need to update it there (unfortunately not me since I am no longer a user). Looks like another issue I recall encountering was fixed too: see https://github.com/serprex/byteplay/issues/3 & https://github.com/serprex/byteplay/issues/5.

**Comment by ndawe** [comment]
Closing this as it's now fixed in #745
