### ISSUE TITLE
root2hdf5 does not respect inheritance

### ISSUE THREAD

**Issue by riga** [rootpy/rootpy#672]
Hey guys,

first of all : great work =)

I'm currently testing the root(tree)2hdf5 functionality to convert a root file that contains a TNtuple.
[rootpy walks through the file with ``class_pattern="TTree"``](https://github.com/rootpy/rootpy/blob/master/rootpy/root2hdf5.py#L247), which skips all instances of TNtuple. This is not the behavior I would expect since a TNtuple *is* a TTree. IMHO, ``class_pattern`` is the problem here. I would either use something like ``class_regexp`` or pass a class reference to compare with ``isinstance`` in [rootpy.io.file._DirectoryBase.walk](https://github.com/rootpy/rootpy/blob/master/rootpy/io/file.py#L505).

I'll try to create a PR soon.

Edit:
I just created PR #673.

**Comment by ndawe** [comment]
Yes, thanks for taking care of this. class_pattern just supports unix-like filename matching through fnmatch and the advantage is it avoids reading in all objects from the file since the class name is available through the TKeys. So it is potentially a bit faster. But we definitely need class_ref too as you point out. Merging your PR.
